In [1]:
!which python
!conda list mypackage

/home/vgmduarte/code/miniconda3/envs/python_snippets/bin/python
# packages in environment at /home/vgmduarte/code/miniconda3/envs/python_snippets:
#
# Name                    Version                   Build  Channel
mypackage                 0.1.dev0                  dev_0    <develop>


In [2]:
# %load snippets/simple.py
'''Simple notebook setup.'''
%reload_ext autoreload
%autoreload 2

import numpy as np
import mypackage
from mypackage import mymodule
from mypackage.mymodule import myfunc

In [3]:
mypackage.mymodule.myfunc(2, 3,4,5, a=2, b=3, c=5)

2 is a placed arg
(3, 4, 5) is a tuple
{'a': 2, 'b': 3, 'c': 5} is a dictionary


array([3, 4, 5])

In [4]:
mymodule.myfunc(2, 3,4,5, a=2, b=3, c=5)

2 is a placed arg
(3, 4, 5) is a tuple
{'a': 2, 'b': 3, 'c': 5} is a dictionary


array([3, 4, 5])

In [5]:
myfunc(2, 3,4,5, a=2, b=3, c=5)

2 is a placed arg
(3, 4, 5) is a tuple
{'a': 2, 'b': 3, 'c': 5} is a dictionary


array([3, 4, 5])